#!/bin/bash

# Modify these according to your own installations of packages.
orca_ver=6.1.1
openmpi_ver=4.1.8
orca_path="/opt/orca-${orca_ver}"
openmpi_path="${orca_path}/openmpi-${openmpi_ver}"

  
if [[ ! -x "${orca_path}/orca" ]]; then
  echo "ORCA not found." >&2
  return 1
fi
if [[ ! -d "${openmpi_path}/lib" ]]; then
  echo "OpenMPI not installed." >&2
  return 1
fi

backup_file() {
	if [[ -e "${1}" ]]; then
		if [[ -e "${1}.bak" ]]; then
			backup_file "${1}.bak"
		fi
		mv "${1}" "${1}.$(stat -c '%y' ${1} | cut -d '.' -f 1 | sed 's/-\| \|://g').bak"
	fi
}

orca_ser() {
  for file1 in "$@"; do	
	sleep 1
	backup_file "${file1}.log"
    "${orca_path}/orca" "${file1}" > "${file1}.log"; 
  done; 
}

orca_par() {
  for file1 in "$@"; do
	sleep 1
	backup_file "${file1}.log"
    "${orca_path}/orca" "${file1}" > "${file1}.log" &; 
  done; 
}

if [[ ! ${PATH} =~ ${orca_path} ]]; then
  export PATH="${orca_path}"${PATH:+":$PATH"}
fi
if [[ ! ${PATH} =~ "${openmpi_path}/bin" ]]; then
  export PATH="${openmpi_path}/bin"${PATH:+":$PATH"}
fi
if [[ ! ${LD_LIBRARY_PATH} =~ ${orca_path} ]]; then  
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+"${LD_LIBRARY_PATH}:"}${orca_path}
fi
if [[ ! ${LD_LIBRARY_PATH} =~ "${openmpi_path}/lib" ]]; then  
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+"${LD_LIBRARY_PATH}:"}"${openmpi_path}/lib"
fi
