#!/bin/bash

orca_path=/opt/orca-4.0.1.2
openmpi_path=/usr/local/lib/openmpi-2.0.2

backup_file() {
	if [[ -e "${1}.bak" ]]; then
		backup_file "${1}.bak"
	fi
	mv "${1}" "${1}.bak"
}
    

if [[ ! -x "${orca_path}/orca" ]]; then
  echo "ORCA not found." >&2
  return 1
fi
if [[ ! -d "${openmpi_path}/lib" ]]; then
  echo "OpenMPI 2.0.2 not installed." >&2
  return 2
fi

orca() {
  for file1 in "$@"; do
		if [[ -e "${file1}.log" ]]; then
			backup_file "${file1}.log"
		fi
    "${orca_path}/orca" "${file1}" > "${file1}.log"; 
  done; 
}

if [[ ! ${PATH} =~ ${openmpi_path} ]]; then
  export PATH="${openmpi_path}/bin":$PATH
fi
if [[ ! ${LD_LIBRARY_PATH} =~ ${orca_path} ]]; then  
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH+"${LD_LIBRARY_PATH}:"}${orca_path}
fi
if [[ ! ${LD_LIBRARY_PATH} =~ "${openmpi_path}/lib" ]]; then  
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH+"${LD_LIBRARY_PATH}:"}"${openmpi_path}/lib"
fi
