#!/bin/bash

orca_path=/opt/orca-4.0.1.2
openmpi_path=/usr/local/lib/openmpi-2.0.2

orca() { $orca_path/orca $1 > $1.log; }
if [[ ! ${PATH} =~ ${openmpi_path} ]]; then
  export PATH=/usr/local/lib/openmpi-2.0.2/bin:$PATH
fi
if [[ ! ${LD_LIBRARY_PATH} =~ ${openmpi_path} ]]; then  
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/openmpi-2.0.2/lib
fi
